Error: cannot import name 'views' from 'backend' (/Users/hans/Projects/Usach/geospatialWebapp/backend/backend/__init__.py)
Traceback (most recent call last):
  File "/Users/hans/Projects/Usach/geospatialWebapp/backend/combined_server.py", line 112, in main
    execute_from_command_line(sys.argv)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 74, in execute
    super().execute(*args, **options)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 111, in handle
    self.run(**options)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 120, in run
    self.inner_run(None, **options)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/hans/Projects/Usach/geospatialWebapp/backend/backend/urls.py", line 2, in <module>
    from . import views
ImportError: cannot import name 'views' from 'backend' (/Users/hans/Projects/Usach/geospatialWebapp/backend/backend/__init__.py)
